version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and test:
    excutor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run:
            name: Install project dependencies
            command: npm install
          - run:
            name: Run Lint
            command: npm run lint
          - run:
            name: Run Formatter (Check format)
            command: npm run check-format:all
          - run:
            name: Build project
            command: npm run build
workflows:
  build-and-test:
    jobs:
      - build-and-test
